name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion! Please describe your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
      description: What problem does this solve or what opportunity does it address?
      placeholder: "Currently, the skill doesn't support..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: "The skill could..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered other approaches?

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - New template type
        - Analysis improvement
        - Output formatting
        - Documentation
        - Configuration options
        - Other

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Examples, references, or other details
